# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6602853425afe9f2b4ca05fd280c54c5af838b3e6423926dd1c07df9d834ac185e3a9b231e9bb2f52871adf23ac3ddb344ef6fcbe66e511693d128877102c541

test:
  secret_key_base: 75995e415c42fdecb450a4a26cb39a138d24d12c56307180712e0ac7527cd12097108449a1345bc327578775976c75e224a81fa23e265cab94d68a8eba9f7529

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
